-- Migration generated by migrate_wordpress.mjs
PRAGMA defer_foreign_keys = ON;
BEGIN TRANSACTION;
INSERT INTO authors (id, slug, name, email) VALUES (1, 'jdoe', 'John Doe', 'john@example.com');
INSERT INTO categories (id, slug, name) VALUES (1, 'news', 'News');
INSERT INTO tags (id, slug, name) VALUES (1, 'breaking', 'Breaking News');
INSERT INTO media (id, r2_key, filename, mime_type, size_bytes) VALUES (1, '2025/01/image.jpg', '2025/01/image.jpg', 'image/jpeg', 0);
INSERT INTO posts (id, slug, title, content, excerpt, status, published_at, author_id, category_id, cover_media_id) VALUES (1, 'hello-world', 'Hello World', '<p>Welcome to WordPress. This is your first post. Edit or delete it, then start writing!</p>', NULL, 'published', '2025-01-02 10:00:00', 1, 1, 1);
COMMIT;