name = "webapp"
compatibility_date = "2024-09-23"

# D1 Databases
[[d1_databases]]
binding = "DB"
database_name = "webapp-prod-v2"
database_id = "16c980b7-4c6f-45df-b315-b4b2d5b7ceaa"

# KV Namespaces
[[kv_namespaces]]
binding = "KV"
id = "ef54494bcf754b889308976043a8c47b"

[[kv_namespaces]]
binding = "CACHE"
id = "627e53560f4845948da9ef9f69a842cc"

# R2 Buckets
[[r2_buckets]]
binding = "R2"
bucket_name = "webapp-media"

[vars]
PUBLIC_BASE_URL = "https://diario.dopovo.com.br"
