import fs from 'fs';
import xml2js from 'xml2js';
import path from 'path';

// Configuração
const INPUT_FILE = process.argv[2];
const OUTPUT_FILE = 'migration_output.sql';

if (!INPUT_FILE) {
    console.error('Uso: node scripts/migrate_wordpress.mjs <caminho-para-o-arquivo-xml>');
    process.exit(1);
}

const parser = new xml2js.Parser();

function escapeSql(str) {
    if (str === null || str === undefined) return 'NULL';
    str = String(str);
    // Substitui aspas simples por duas aspas simples para escapar no SQL
    return "'" + str.replace(/'/g, "''") + "'";
}

function formatDate(dateStr) {
    if (!dateStr || dateStr === '0000-00-00 00:00:00') return 'NULL';
    // SQLite accepts ISO strings or space separated. WXR usually has YYYY-MM-DD HH:MM:SS
    return escapeSql(dateStr);
}

// Mapas para IDs (Old ID -> New ID)
const authorMap = new Map(); // login -> id
const categoryMap = new Map(); // old_nicename -> new_id
const tagMap = new Map(); // old_slug -> new_id
const mediaMap = new Map(); // attachment_wp_id -> media_id/r2_key

let sqlOutput = [];

function addSql(sql) {
    sqlOutput.push(sql);
}

addSql('-- Migration generated by enhanced migrate_wordpress.mjs');
addSql('PRAGMA defer_foreign_keys = ON;');
addSql('BEGIN TRANSACTION;');

// 0. Disable constraints during import for flexibility
addSql('DELETE FROM posts_tags;');
addSql('DELETE FROM posts;');
addSql('DELETE FROM categories;');
addSql('DELETE FROM tags;');
addSql('DELETE FROM media;');
addSql('DELETE FROM authors;');

fs.readFile(INPUT_FILE, function (err, data) {
    if (err) {
        console.error('Erro ao ler arquivo:', err);
        return;
    }

    parser.parseString(data, function (err, result) {
        if (err) {
            console.error('Erro ao fazer parse do XML:', err);
            return;
        }

        const channel = result.rss.channel[0];

        // 1. Authors
        console.log('Processando Autores...');
        if (channel['wp:author']) {
            channel['wp:author'].forEach((author, index) => {
                const login = author['wp:author_login'][0];
                const email = author['wp:author_email'][0];
                const display_name = author['wp:author_display_name'][0];
                const newId = index + 1;
                authorMap.set(login, newId);
                addSql(`INSERT INTO authors (id, slug, name, email) VALUES (${newId}, ${escapeSql(login)}, ${escapeSql(display_name)}, ${escapeSql(email)});`);
            });
        }

        // 2. Categories (Flat first, then hierarchy if needed)
        console.log('Processando Categorias...');
        if (channel['wp:category']) {
            channel['wp:category'].forEach((cat, index) => {
                const nicename = cat['wp:category_nicename'][0];
                const name = cat['wp:cat_name'][0];
                const description = cat['wp:category_description'] ? cat['wp:category_description'][0] : '';
                const newId = index + 1;
                categoryMap.set(nicename, newId);
                addSql(`INSERT INTO categories (id, slug, name, description) VALUES (${newId}, ${escapeSql(nicename)}, ${escapeSql(name)}, ${escapeSql(description)});`);
            });
        }

        // 3. Tags
        console.log('Processando Tags...');
        if (channel['wp:tag']) {
            channel['wp:tag'].forEach((tag, index) => {
                const slug = tag['wp:tag_slug'][0];
                const name = tag['wp:tag_name'][0];
                const newId = index + 1;
                tagMap.set(slug, newId);
                addSql(`INSERT INTO tags (id, slug, name) VALUES (${newId}, ${escapeSql(slug)}, ${escapeSql(name)});`);
            });
        }

        const items = channel.item || [];
        const attachments = items.filter(i => i['wp:post_type'][0] === 'attachment');
        const posts = items.filter(i => i['wp:post_type'][0] === 'post');
        const pages = items.filter(i => i['wp:post_type'][0] === 'page');

        // 4. Media
        console.log('Processando Mídia...');
        attachments.forEach((att, index) => {
            const wpId = att['wp:post_id'][0];
            const url = att['guid'] ? att['guid'][0]._ : '';
            const filename = path.basename(url);
            const r2_key = filename; // Placeholder for R2 migration
            const newId = index + 1;
            mediaMap.set(wpId, newId);
            addSql(`INSERT INTO media (id, r2_key, filename, mime_type, size_bytes) VALUES (${newId}, ${escapeSql(r2_key)}, ${escapeSql(filename)}, 'image/jpeg', 0);`);
        });

        // 5. Posts
        console.log('Processando Posts...');
        posts.forEach((post, index) => {
            const wpId = post['wp:post_id'][0];
            const title = post.title[0];
            const slug = post['wp:post_name'][0];
            const content = post['content:encoded'][0];
            const excerpt = post['excerpt:encoded'][0];
            const status = post['wp:status'][0] === 'publish' ? 'published' : 'draft';
            const date = post['wp:post_date'][0];
            const authorLogin = post['dc:creator'][0];
            const authorId = authorMap.get(authorLogin) || 1;

            // Chapeu selection logic
            const meta = post['wp:postmeta'] || [];
            const chapeuMeta = meta.find(m => m['wp:meta_key'][0] === 'chapeu');
            const hat = chapeuMeta ? chapeuMeta['wp:meta_value'][0] : null;

            // Category assignment
            let categoryId = 1;
            const postTags = [];
            if (post.category) {
                post.category.forEach(c => {
                    const domain = c.$ ? c.$.domain : '';
                    const nicename = c.$ ? c.$.nicename : '';
                    if (domain === 'category') {
                        const foundId = categoryMap.get(nicename);
                        if (foundId) categoryId = foundId;
                    } else if (domain === 'post_tag') {
                        const foundId = tagMap.get(nicename);
                        if (foundId) postTags.push(foundId);
                    }
                });
            }

            // Featured Image
            let coverMediaId = 'NULL';
            const thumbMeta = meta.find(m => m['wp:meta_key'][0] === '_thumbnail_id');
            if (thumbMeta) {
                const thumbWpId = thumbMeta['wp:meta_value'][0];
                if (mediaMap.has(thumbWpId)) {
                    coverMediaId = mediaMap.get(thumbWpId);
                }
            }

            const newPostId = index + 1;
            addSql(`INSERT INTO posts (id, slug, title, hat, content, excerpt, status, published_at, created_at, updated_at, author_id, category_id, cover_media_id) VALUES (${newPostId}, ${escapeSql(slug)}, ${escapeSql(title)}, ${escapeSql(hat)}, ${escapeSql(content)}, ${escapeSql(excerpt)}, '${status}', ${formatDate(date)}, ${formatDate(date)}, ${formatDate(date)}, ${authorId}, ${categoryId}, ${coverMediaId});`);

            // 6. Post-Tag Relationship
            postTags.forEach(tId => {
                addSql(`INSERT INTO posts_tags (post_id, tag_id) VALUES (${newPostId}, ${tId});`);
            });
        });

        // 7. Pages
        console.log('Processando Páginas...');
        pages.forEach((page, index) => {
            const title = page.title[0];
            const slug = page['wp:post_name'][0];
            const content = page['content:encoded'][0];
            const status = page['wp:status'][0] === 'publish' ? 1 : 0;
            addSql(`INSERT INTO pages (slug, title, content, is_active) VALUES (${escapeSql(slug)}, ${escapeSql(title)}, ${escapeSql(content)}, ${status});`);
        });

        addSql('COMMIT;');
        fs.writeFileSync(OUTPUT_FILE, sqlOutput.join('\n'));
        console.log(`Sucesso! Arquivo ${OUTPUT_FILE} gerado.`);
    });
});
