import fs from 'fs';
import xml2js from 'xml2js';
import path from 'path';

// Configuração
const INPUT_FILE = process.argv[2];
const OUTPUT_FILE = 'migration_output.sql';

if (!INPUT_FILE) {
    console.error('Uso: node scripts/migrate_wordpress.mjs <caminho-para-o-arquivo-xml>');
    process.exit(1);
}

const parser = new xml2js.Parser();

function escapeSql(str) {
    if (!str) return 'NULL';
    // Substitui aspas simples por duas aspas simples para escapar no SQL
    return "'" + str.replace(/'/g, "''") + "'";
}

function formatDate(dateStr) {
    if (!dateStr || dateStr === '0000-00-00 00:00:00') return 'NULL';
    return escapeSql(dateStr.replace(' ', 'T') + 'Z'); // Formato ISO simplificado ou manter string se SQLite aceitar
}

// Mapas para IDs (Old ID -> New ID)
const authorMap = new Map(); // login -> id
const categoryMap = new Map(); // old_term_id -> new_id
const tagMap = new Map(); // old_slug -> new_id (tags não tem ID fixo no export as vezes, usa slug)
const itemsMap = new Map(); // post_id (WP) -> new_id (D1) - PODE ser 1:1 se limparmos a tabela antes
const mediaMap = new Map(); // attachment_id -> media_id

let sqlOutput = [];

// Helper para adicionar SQL
function addSql(sql) {
    sqlOutput.push(sql);
}

// Cabeçalho do SQL
addSql('-- Migration generated by migrate_wordpress.mjs');
addSql('PRAGMA defer_foreign_keys = ON;');
addSql('BEGIN TRANSACTION;');

fs.readFile(INPUT_FILE, function (err, data) {
    if (err) {
        console.error('Erro ao ler arquivo:', err);
        return;
    }

    parser.parseString(data, function (err, result) {
        if (err) {
            console.error('Erro ao fazer parse do XML:', err);
            return;
        }

        const channel = result.rss.channel[0];

        console.log('Processando Autores...');
        // 1. Authors
        if (channel['wp:author']) {
            channel['wp:author'].forEach((author, index) => {
                const login = author['wp:author_login'][0];
                const email = author['wp:author_email'][0];
                const display_name = author['wp:author_display_name'][0];

                // Assumindo IDs sequenciais novos para evitar conflitos, ou preservar IDs se possível?
                // Vamos criar IDs novos sequenciais para garantir integridade no novo banco
                const newId = index + 1;
                authorMap.set(login, newId);

                addSql(`INSERT INTO authors (id, slug, name, email) VALUES (${newId}, ${escapeSql(login)}, ${escapeSql(display_name)}, ${escapeSql(email)});`);
            });
        }

        const categorySlugMap = new Map(); // slug -> new_id

        console.log('Processando Categorias...');
        // 2. Categories
        if (channel['wp:category']) {
            channel['wp:category'].forEach((cat, index) => {
                const term_id = cat['wp:term_id'][0];
                const nicename = cat['wp:category_nicename'][0];
                const name = cat['wp:cat_name'][0];

                const newId = index + 1;
                categoryMap.set(term_id, newId);
                categorySlugMap.set(nicename, newId);

                // Parent processamento seria ideal depois, mas vamos ignorar parent complexo por agora
                addSql(`INSERT INTO categories (id, slug, name) VALUES (${newId}, ${escapeSql(nicename)}, ${escapeSql(name)});`);
            });
        }

        // Atualizar parents das categorias (segunda passada se fosse array, mas aqui simplificamos)
        // Se precisar de hierarquia exata, teria que processar em duas etapas.

        console.log('Processando Tags...');
        // 3. Tags
        if (channel['wp:tag']) {
            channel['wp:tag'].forEach((tag, index) => {
                const slug = tag['wp:tag_slug'][0];
                const name = tag['wp:tag_name'][0];

                const newId = index + 1;
                tagMap.set(slug, newId);

                addSql(`INSERT INTO tags (id, slug, name) VALUES (${newId}, ${escapeSql(slug)}, ${escapeSql(name)});`);
            });
        }

        // Separar posts e attachments
        const items = channel.item || [];
        const posts = items.filter(i => i['wp:post_type'][0] === 'post');
        const pages = items.filter(i => i['wp:post_type'][0] === 'page');
        const attachments = items.filter(i => i['wp:post_type'][0] === 'attachment');

        console.log(`Encontrados: ${posts.length} posts, ${pages.length} pages, ${attachments.length} attachments.`);

        // 4. Media (Attachments)
        console.log('Processando Mídia...');
        attachments.forEach((att, index) => {
            const postId = att['wp:post_id'][0];
            const url = att['guid'][0]._; // URL original
            const title = att.title[0];
            // Tenta pegar metadados se existirem
            const meta = att['wp:postmeta'] || [];
            const metaFile = meta.find(m => m['wp:meta_key'][0] === '_wp_attached_file');

            const filename = metaFile ? metaFile['wp:meta_value'][0] : path.basename(url);
            const r2_key = filename; // Placeholder: usar o filename como chave R2

            const newId = index + 1;
            mediaMap.set(postId, newId);

            // Simples inserção de mídia
            addSql(`INSERT INTO media (id, r2_key, filename, mime_type, size_bytes) VALUES (${newId}, ${escapeSql(r2_key)}, ${escapeSql(filename)}, 'image/jpeg', 0);`);
        });

        // 5. Posts
        console.log('Processando Posts...');
        posts.forEach((post, index) => {
            const wpId = post['wp:post_id'][0];
            const title = post.title[0];
            const slug = post['wp:post_name'][0];
            const content = post['content:encoded'][0];
            const excerpt = post['excerpt:encoded'][0];
            const status = post['wp:status'][0] === 'publish' ? 'published' : 'draft';
            const date = post['wp:post_date'][0];

            // Autor
            const creator = post['dc:creator'][0];
            const authorId = authorMap.get(creator) || 1; // Fallback para id 1

            // Categoria (pega a primeira)
            let categoryId = 1;
            if (post.category) {
                for (const c of post.category) {
                    if (c.$ && c.$.domain === 'category' && c.$.nicename) {
                        const foundId = categorySlugMap.get(c.$.nicename);
                        if (foundId) {
                            categoryId = foundId;
                            break; // Usa a primeira encontrada
                        }
                    }
                }
            }

            // Imagem Destacada
            let coverMediaId = 'NULL';
            const meta = post['wp:postmeta'] || [];
            const thumbMeta = meta.find(m => m['wp:meta_key'][0] === '_thumbnail_id');
            if (thumbMeta) {
                const thumbId = thumbMeta['wp:meta_value'][0];
                if (mediaMap.has(thumbId)) {
                    coverMediaId = mediaMap.get(thumbId);
                }
            }

            // Se slug vazio (post rascunho as vezes), gera um
            const finalSlug = slug || `post-${wpId}`;

            // Inserir Post
            // IMPORTANTE: id setado manualmente para manter referencias se precisar, ou sequencial?
            // Vamos usar sequencial novo para limpar buracos
            const newPostId = index + 1;

            addSql(`INSERT INTO posts (id, slug, title, content, excerpt, status, published_at, author_id, category_id, cover_media_id) VALUES (${newPostId}, ${escapeSql(finalSlug)}, ${escapeSql(title)}, ${escapeSql(content)}, ${escapeSql(excerpt)}, '${status}', ${formatDate(date)}, ${authorId}, ${categoryId}, ${coverMediaId});`);
        });
    });

    addSql('COMMIT;');

    fs.writeFileSync(OUTPUT_FILE, sqlOutput.join('\n'));
});
